"""Rasterise the thesis figures so they survive the Word conversion.

Inline SVG does not travel into DOCX, and no SVG rasteriser is installable in
this environment. A general renderer would be the wrong tool anyway: these
figures are generated by this project, from a small and known set of elements,
so a parser for exactly that set is both shorter and more predictable than a
partial implementation of the SVG specification.

Handled: rect, circle, line, path (straight segments only), text with anchors.
Styling comes from the class attribute, resolved through STYLE below, because
the figures inherit their colours from the document stylesheet rather than
carrying inline attributes.

Anything unrecognised is skipped and counted, and the caller is told, so a
figure that silently loses half its marks cannot pass as rendered.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyArrow, Rectangle

# the print palette: the same hues as the screen build, on white
INK, INK2, MUTED = "#1a1815", "#45403a", "#6b665e"
RULE, ACCENT, PANEL = "#e2ddd5", "#9a3412", "#ffffff"
S = {"s1": "#2a78d6", "s2": "#eb6834", "s3": "#1baf7a", "s4": "#c4bfb1"}

STYLE = {
    **{k: {"fill": v} for k, v in S.items()},
    "cl":     {"color": INK2, "size": 12},
    "cm":     {"color": MUTED, "size": 10.5},
    "cv-num": {"color": INK, "size": 11.5, "mono": True},
    "cv-in":  {"color": INK, "size": 12, "mono": True, "weight": "600"},
    "ref":    {"stroke": MUTED, "lw": 1, "dash": (3, 3)},
    "stem":   {"stroke": RULE, "lw": 1.5},
    "ci":     {"stroke": MUTED, "lw": 1.5},
    "gap":    {"fill": RULE},
    "dbox":   {"fill": PANEL, "stroke": RULE, "lw": 1},
    "dpill":  {"fill": PANEL, "stroke": RULE, "lw": 1},
    "darr":   {"stroke": RULE, "lw": 1.3},
    "dfill":  {"fill": RULE},
    "dt":     {"color": INK, "size": 12, "weight": "600"},
    "dsub":   {"color": MUTED, "size": 10.5},
    "dhead":  {"color": ACCENT, "size": 9.5, "weight": "700"},
}
ANCHOR = {"start": "left", "middle": "center", "end": "right"}

# SVG lengths are CSS pixels; matplotlib sizes text in points. Passing the pixel
# value straight through rendered every label about a third too large, which
# produced overlaps in the raster that do not exist in the browser and sent me
# looking for layout bugs that were not there.
PX_TO_PT = 0.75


def _attrs(tag: str) -> dict:
    return dict(re.findall(r'([\w:-]+)="([^"]*)"', tag))


def _sty(a: dict) -> dict:
    out = {}
    for cls in a.get("class", "").split():
        out.update(STYLE.get(cls, {}))
    # an inline attribute wins over the class, matching SVG's own precedence
    for svg_attr, key in (("fill", "fill"), ("stroke", "stroke")):
        v = a.get(svg_attr)
        if v and v != "none":
            out[key] = _rgba(v)
        elif v == "none":
            out.pop(key, None)
    if a.get("stroke-width"):
        out["lw"] = float(a["stroke-width"])
    return out


# the figures reference the document's custom properties inline; the print
# build has no stylesheet, so they are resolved to their concrete values here
VARS = {
    "--c-blue": S["s1"], "--c-orange": S["s2"], "--c-green": S["s3"],
    "--c-grey": S["s4"], "--accent": ACCENT, "--muted": MUTED,
    "--rule": RULE, "--ink": INK, "--ink-2": INK2, "--panel": PANEL,
}


def _rgba(v: str):
    """matplotlib understands hex; rgba() and var() need resolving."""
    m = re.match(r"var\((--[a-z0-9-]+)", v)
    if m:
        return VARS.get(m.group(1), MUTED)
    m = re.match(r"rgba?\(([\d.]+),\s*([\d.]+),\s*([\d.]+)(?:,\s*([\d.]+))?\)", v)
    if not m:
        return v
    r, g, b = (float(m.group(i)) / 255 for i in (1, 2, 3))
    return (r, g, b, float(m.group(4)) if m.group(4) else 1.0)


def _f(a: dict, k: str, d: float = 0.0) -> float:
    try:
        return float(a.get(k, d))
    except ValueError:
        return d


def render(svg: str, out: Path, dpi: int = 200) -> tuple[Path, int]:
    """Draw one SVG to a PNG. Returns the path and the count of skipped marks."""
    vb = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg)
    W, H = (float(vb.group(1)), float(vb.group(2))) if vb else (760.0, 300.0)

    fig, ax = plt.subplots(figsize=(W / 100, H / 100), dpi=dpi)
    ax.set_xlim(0, W)
    ax.set_ylim(H, 0)          # SVG y grows downward
    ax.axis("off")
    fig.patch.set_facecolor("white")
    skipped = 0


    # class, stroke-width and dash are set on the enclosing <g> and inherited by
    # the marks inside it. Reading only each element's own attributes resolves
    # every rect to no stroke and zero width, which draws nothing at all, so the
    # group's attributes are pushed down before parsing.
    def _inherit(src):
        keys = ("class", "stroke-width", "stroke-dasharray", "opacity")

        def expand(g):
            gattr, inner = g.group(1), g.group(2)
            carry = {k: v.group(1) for k in keys
                     for v in [re.search(k + r'="([^"]*)"', gattr)] if v}
            if not carry:
                return inner

            def push(tag):
                head = tag.group(0)
                extra = "".join(f' {k}="{v}"' for k, v in carry.items()
                                if not re.search(k + r'="', head))
                return head[:-1] + extra + ">"

            return re.sub(r"<(?:rect|circle|line|path|polygon|polyline|text)\b[^>]*>",
                          push, inner)

        prev = None
        while prev != src:
            prev = src
            src = re.sub(r"<g\b([^>]*)>((?:(?!<g\b).)*?)</g>", expand, src, flags=re.S)
        return src

    svg = _inherit(svg)

    for m in re.finditer(
            r"<(rect|circle|line|path|polygon|polyline|text)\b([^>]*)>(?:([^<]*)</text>)?", svg):
        kind, a, txt = m.group(1), _attrs(m.group(2)), m.group(3)
        s = _sty(a)

        if kind == "rect":
            ax.add_patch(Rectangle(
                (_f(a, "x"), _f(a, "y")), _f(a, "width"), _f(a, "height"),
                facecolor=s.get("fill", "none"), edgecolor=s.get("stroke", "none"),
                linewidth=s.get("lw", 0)))
        elif kind == "circle":
            ax.add_patch(Circle((_f(a, "cx"), _f(a, "cy")), _f(a, "r"),
                                facecolor=s.get("fill", "none"),
                                edgecolor=s.get("stroke", "none"),
                                linewidth=s.get("lw", 0)))
        elif kind == "line":
            kw = {"dashes": s["dash"]} if s.get("dash") else {}
            ax.plot([_f(a, "x1"), _f(a, "x2")], [_f(a, "y1"), _f(a, "y2")],
                    color=s.get("stroke", MUTED), linewidth=s.get("lw", 1),
                    solid_capstyle="butt", **kw)
        elif kind in ("polygon", "polyline"):
            pts = [tuple(map(float, q.split(",")))
                   for q in a.get("points", "").split() if "," in q]
            if len(pts) >= 2:
                xs = [q[0] for q in pts]
                ys = [q[1] for q in pts]
                if kind == "polygon" and s.get("fill"):
                    ax.fill(xs, ys, facecolor=s["fill"],
                            edgecolor=s.get("stroke", "none"),
                            linewidth=s.get("lw", 0))
                else:
                    ax.plot(xs, ys, color=s.get("stroke", MUTED),
                            linewidth=s.get("lw", 1))
            else:
                skipped += 1
        elif kind == "path":
            pts = re.findall(r"[ML]\s*([-\d.]+),([-\d.]+)", a.get("d", ""))
            if len(pts) >= 2:
                xs = [float(x) for x, _ in pts]
                ys = [float(y) for _, y in pts]
                kw = {"dashes": s["dash"]} if s.get("dash") else {}
                ax.plot(xs, ys, color=s.get("stroke", RULE),
                        linewidth=s.get("lw", 1.2), **kw)
                if "marker-end" in a:      # arrowheads are markers in the SVG
                    dx, dy = xs[-1] - xs[-2], ys[-1] - ys[-2]
                    n = (dx * dx + dy * dy) ** 0.5 or 1
                    ax.add_patch(FancyArrow(
                        xs[-1] - dx / n * 4, ys[-1] - dy / n * 4,
                        dx / n * 4, dy / n * 4, width=0.1, head_width=5,
                        head_length=5, color=s.get("stroke", RULE), length_includes_head=True))
            else:
                skipped += 1
        elif kind == "text":
            if txt is None:
                skipped += 1
                continue
            body = (txt.replace("&#183;", "·").replace("&amp;", "&")
                       .replace("&minus;", "−").replace("&#8594;", "→"))
            if not body.strip():
                continue
            ax.text(_f(a, "x"), _f(a, "y"), body,
                    color=s.get("color", INK), fontsize=s.get("size", 11) * PX_TO_PT,
                    ha=ANCHOR.get(a.get("text-anchor", "start"), "left"),
                    va="baseline",
                    fontweight="bold" if s.get("weight") in ("600", "700") else "normal",
                    family="monospace" if s.get("mono") else "sans-serif")

    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=dpi, bbox_inches="tight", pad_inches=0.06, facecolor="white")
    plt.close(fig)
    return out, skipped


def render_all(html: str, outdir: Path) -> dict[str, Path]:
    """Every <figure> SVG in the document, keyed by its caption label."""
    made, total_skipped = {}, 0
    for fig in re.findall(r"<figure>.*?</figure>", html, flags=re.S):
        svg = re.search(r"<svg\b.*?</svg>", fig, flags=re.S)
        cap = re.search(r"<figcaption>(.*?)</figcaption>", fig, flags=re.S)
        if not svg:
            continue
        label = re.sub(r"<[^>]+>", "", cap.group(1)) if cap else ""
        label = re.sub(r"\s+", " ", label).strip()
        key = re.match(r"((?:Figure|Table)\s*\d+)", label)
        key = key.group(1).replace(" ", "") if key else hashlib.md5(
            svg.group(0).encode()).hexdigest()[:8]
        path, skipped = render(svg.group(0), outdir / f"{key}.png")
        total_skipped += skipped
        made[key] = path
    if total_skipped:
        print(f"  note: {total_skipped} unrecognised mark(s) skipped across all figures")
    return made


if __name__ == "__main__":
    import sys
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "thesis_source.html")
    out = Path("reports/figures/thesis_png")
    made = render_all(src.read_text(encoding="utf-8", errors="replace"), out)
    print(f"rendered {len(made)} figures -> {out}")
