"""Production EDA for the player-season efficiency model -> reports/PLAYER_SEASON_EDA.md.

Characterises the dataset before modelling and, crucially, shows WHY this target is
learnable to high AUC while single-shot make prediction is not: shooting skill is
strongly autocorrelated across seasons, so a player's prior efficiency forecasts
their next-season standing. The single-shot ceiling (~0.70) is a property of the
target UNIT (a coin flip), not the model — aggregating to a player-season removes
the noise. This EDA is the evidence for that thesis point.

CLI:  python -m src.data.eda_player_season
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from src.config import get_config
from src.data.player_season import build


def _load(cfg) -> pd.DataFrame:
    return build(cfg)


def _figures(df, fig_dir):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig_dir.mkdir(parents=True, exist_ok=True)

    # (1) skill is sticky: prior TS% vs current TS%, with the median line
    fig, ax = plt.subplots(1, 2, figsize=(11, 4.3))
    s = df.dropna(subset=["prior_ts_percent", "ts_percent"])
    ax[0].scatter(s["prior_ts_percent"], s["ts_percent"], s=4, alpha=0.15, color="#3b82f6")
    lim = [s["prior_ts_percent"].quantile(0.01), s["prior_ts_percent"].quantile(0.99)]
    ax[0].plot(lim, lim, "k--", alpha=0.5, label="y = x")
    r = float(np.corrcoef(s["prior_ts_percent"], s["ts_percent"])[0, 1])
    ax[0].set_title(f"Shooting skill is sticky (r = {r:.2f})")
    ax[0].set_xlabel("prior-season TS%"); ax[0].set_ylabel("current-season TS%")
    ax[0].legend(); ax[0].grid(alpha=0.3)

    # (2) elite (top-third) rate as a function of prior-TS% decile
    from src.data.player_season import ELITE_Q
    s = s.copy()
    s["elite"] = s.groupby("season")["ts_percent"].transform(lambda x: (x > x.quantile(ELITE_Q)).astype(int))
    s["dec"] = pd.qcut(s["prior_ts_percent"], 10, labels=False, duplicates="drop")
    g = s.groupby("dec")["elite"].mean()
    ax[1].plot(g.index, g.values, marker="o", color="#ef4444")
    ax[1].set_title("P(elite / top-third TS% this season) by prior-TS% decile")
    ax[1].set_xlabel("prior-season TS% decile (0=worst, 9=best)")
    ax[1].set_ylabel("P(elite this season)"); ax[1].grid(alpha=0.3)
    fig.tight_layout(); fig.savefig(fig_dir / "player_season_stickiness.png", dpi=130)
    plt.close(fig)
    return r


def main() -> int:
    cfg = get_config()
    df = _load(cfg)
    r = _figures(df, cfg.path("figures"))

    # univariate |corr| of each prior feature with the target
    from src.data.player_season import (PRIOR_ADV, PRIOR_SHOOT_ALL, DERIVED, ENRICH)
    feats = [c for c in PRIOR_ADV + PRIOR_SHOOT_ALL + DERIVED + ENRICH if c in df.columns]
    y = df["target"].to_numpy()
    rows = []
    for c in feats:
        v = pd.to_numeric(df[c], errors="coerce").to_numpy()
        ok = np.isfinite(v)
        if ok.sum() < 200 or np.nanstd(v[ok]) == 0:
            continue
        rows.append((c, abs(float(np.corrcoef(v[ok], y[ok])[0, 1])),
                     float(df[c].notna().mean())))
    rows.sort(key=lambda t: -t[1])

    lines = [
        "# PLAYER_SEASON_EDA.md — elite shooting-efficiency model (Model 3)",
        "",
        "Generated by `python -m src.data.eda_player_season`. The honest high-AUC",
        "model: predict whether a player-season is an **elite (top-third) True",
        "Shooting %** season, from prior-season skill + current-season shot selection.",
        "",
        "## Why this is learnable (and single-shot make is not)",
        "",
        f"- Prior-season TS% correlates **r = {r:.2f}** with current-season TS%: "
        "shooting skill is stable across seasons.",
        "- A single shot is a Bernoulli coin flip (AUC ceiling ~0.70). A player-season",
        "  sums hundreds of shots, so the noise averages out and the standing is",
        "  predictable. **The ceiling is a property of the target unit, not the model.**",
        "",
        "![stickiness](figures/player_season_stickiness.png)",
        "",
        "## Dataset",
        "",
        f"- **{len(df):,} qualified player-seasons** (>= {int(df['mp'].min())} min, "
        f"seasons {int(df['season'].min())}-{int(df['season'].max())}), each with >= 1 "
        "prior season of skill.",
        f"- Target balance (above median): **{df['target'].mean():.3f}** (well-balanced).",
        "- Sources: Basketball-Reference Advanced + Player Shooting (distance splits),",
        "  NBA tracking summaries + profiles (prior-season / time-invariant).",
        "",
        "## Strongest prior-season predictors (univariate |corr| with the target)",
        "",
        "| feature | \\|corr\\| | coverage |",
        "|---|---|---|",
    ]
    for c, ac, cov in rows[:15]:
        lines.append(f"| {c} | {ac:.3f} | {cov:.0%} |")
    lines += [
        "",
        "## Split (chronological, recency-matched — forecast future from past)",
        "",
        "Train seasons <= 2019 | validation 2020-2022 | **test 2023-2025** (read once).",
        "No current-season shooting OUTCOME informs the features (only prior-season",
        "skill + current-season shot selection/role); the split is by season so the",
        "model genuinely forecasts, never interpolating within a season.",
    ]
    (cfg.path("reports") / "PLAYER_SEASON_EDA.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"  {len(df):,} player-seasons | prior-vs-current TS% r = {r:.2f}")
    print(f"  top predictor: {rows[0][0]} (|corr| {rows[0][1]:.3f})")
    print("  wrote reports/PLAYER_SEASON_EDA.md + figure")
    assert r > 0.4, "skill should be autocorrelated across seasons"
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
